### ISSUE TITLE
MEMES.csv битый

### ISSUE THREAD

**Issue by churnikov** [DmitrySerg/memology#1]
MEMES.csv не открывается с помощью `pd.read_csv`

При этом, в memology.ipynb используется другой csv файл. Было бы здорово, если бы можно было воспользоваться csv файлом с текстом мемов 😄

**Comment by DmitrySerg** [comment]
Спасибо большое, что указали на ошибку! 

Случайно сохранил в прошлый раз файл не в utf-8, из-за чего поехали строки текста. Пофиксил, теперь `pd.read_csv` должен работать и можно пользоваться мемами 😄
